title: Striped
author:
  name: Joe Bloggs
  email: 'joe@test.com'
metadata:
    description: 'Striped is a free and responsive theme for **Grav**. Its a port of Striped template by HTML5UP.'
    
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "#"
     icon: facebook
  -  url: "#"
     icon: twitter
  -  url: "#"
     icon: google-plus  

# Main Menu
menu:
  - text: Features
    link: "#features"
  - text: Pricing
    link: "#pricing"
  - text: Screenshots
    link: "#screenshots"
  - text: Testimonials
    link: "#testimonials"
  - text: Subscribe
    link: "#subscribe"    

footer: 
  text: "This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris."
  address:
    title: COME VISIT
    lines:
      - line: 1600 Amphitheatre Parkway
      - line: Mountain View, CA
      - line: 94043 US 
  social_title: Socialize
  contact:
    title: CONTACT US
    lines:
      - text: 647.343.8234
        url: "#"
      - text: 123.456.7890
        url: "#" 
      - text: someone@stripedsite.com
        url: "mailto:someone@stripedsite.com"    
